### ISSUE TITLE
Pooled mapConcurrently

### ISSUE THREAD

**Issue by k0ral** [simonmar/async#13]
The current implementation of `mapConcurrently` triggers a list of asynchronous actions all at once. For large lists, this may have 2 problems : 
* resource consumption is unbounded ;
* some use cases (e.g. network connections) will inherently fail if too many concurrent tasks are executed.

Could the `async` library provide a pooled version of `mapConcurrently` that allows limiting the number of concurrent threads ?
Here is a possible implementation : 

```haskell
{-# LANGUAGE TupleSections #-}
import Control.Concurrent.Async (async, waitAny)
import Data.List                (delete, sortBy)
import Data.Ord                 (comparing)

mapConcurrentlyPooled :: Int -> (a -> IO b) -> [a] -> IO [b]
mapConcurrentlyPooled n tasks args = concurrentlyPooled n $ map tasks args

concurrentlyPooled :: Int -> [IO a] -> IO [a]
concurrentlyPooled n tasks = concurrentlyPooled' n (zip [0..] tasks) [] []

concurrentlyPooled' _ [] [] results = return . map snd $ sortBy (comparing fst) results
concurrentlyPooled' 0 todo ongoing results = do
    (task, newResult) <- waitAny ongoing
    concurrentlyPooled' 1 todo (delete task ongoing) (newResult:results)
concurrentlyPooled' n [] ongoing results = concurrentlyPooled' 0 [] ongoing results
concurrentlyPooled' n ((i, task):otherTasks) ongoing results = do
    t <- async $ (i,) <$> task
    concurrentlyPooled' (n-1) otherTasks (t:ongoing) results
```

**Comment by spl** [comment]
See [jwiegley/async-pool](https://github.com/jwiegley/async-pool).

**Comment by k0ral** [comment]
Thanks for the pointer, that's indeed what I was looking for.

**Comment by simonmar** [comment]
async 2.2.6 includes this functionality in a new module `Control.Concurrent.Stream`: https://github.com/simonmar/async/blob/master/Control/Concurrent/Stream.hs

In particular see `mapConcurrentlyBounded`
