### ISSUE TITLE
Missing documentation: `waitAny []` throws `BlockedIndefinitelyOnSTM`

### ISSUE THREAD

**Issue by runeksvendsen** [simonmar/async#130]
The documentation for the `waitAny*` functions should mention that passing an empty list will make it throw a `BlockedIndefinitelyOnSTM` exception.

If we agree that this is an issue, I would be happy to open a PR that improves the docs in this regard.

**Comment by simonmar** [comment]
Sure. We could also just throw an informative exception in that case, that's probably better.

**Comment by runeksvendsen** [comment]
Also throwing a more informative exception sounds good to me. Although I see no reason for this to replace improved documentation.

Would you prefer we create a new, specific exception type for the purpose or reusing an existing one?
