### ISSUE TITLE
MVar deadlock exceptions cause waitCatch to throw an exception

### ISSUE THREAD

**Issue by snoyberg** [simonmar/async#14]
I originally discovered this problem when working around an [issue with hlint](https://github.com/ndmitchell/hlint/issues/73) (so pinging @ndmitchell, who may be interested). Consider the following program:

``` haskell
import Control.Concurrent
import Control.Concurrent.Async
import Control.Concurrent.MVar
import Control.Exception

main :: IO ()
main = do
    e <- try $ newEmptyMVar >>= takeMVar
    print (e :: Either SomeException Int)

    _ <- forkIO $ do
        e <- try $ newEmptyMVar >>= takeMVar
        print ("thread", e :: Either SomeException Int)
    threadDelay 1000000

    putStrLn "calling async"
    x <- async $ newEmptyMVar >>= takeMVar
    putStrLn "calling waitCatch"
    y <- waitCatch x
    putStrLn "completed waitCatch"
    print (y :: Either SomeException Int)

    putStrLn "Exiting..."
```

There are three logical blocks in this program, each doing essentially the same thing: creating an MVar deadlock exception and trying to catch it. The first approach does it in the main program thread, and the second in a child thread. Both of them work as expected: the exception is caught and printed, and the program continues executing.

However, the third block behaves differently. The MVar exception seems to not be got by the call to `try` in `asyncUsing`, and therefore the `TMVar` is never filled. This means that a later call to `waitCatch` throws an exception, and therefore the program exits prematurely. I've seen the same behavior with `asyncBound` as well, so I do not believe this is related to `rawForkIO`.

Here's an example output from my system:

```
$ ghc --make -O2 -threaded deadlock.hs && ./deadlock 
[1 of 1] Compiling Main             ( deadlock.hs, deadlock.o )
Linking deadlock ...
Left thread blocked indefinitely in an MVar operation
("thread",Left thread blocked indefinitely in an MVar operation)
calling async
calling waitCatch
deadlock: thread blocked indefinitely in an STM transaction
```

I'm on Ubuntu 12.04 64-bit, using GHC 7.8.3, stm-2.4.3 and async-2.0.1.5.

**Comment by simonmar** [comment]
I don't think it actually matters, because the only thing that `f` does is block in STM, and `mask` will be a no-op since blocking is interruptible. `try` would be slightly less efficient.

**Comment by mitchellwrosen** [comment]
@simonmar Thanks for the clarification. I'm still a little bit puzzled - could it not be the case that on the second invocation of

```haskell
atomically (waitSTM x)
```

(with async exceptions masked due to `catch`), the `STM` action might not retry, and if not, any pending asynchronous exception would not be delivered until after the transaction commits? 

A related question - if the transaction gets rolled back and retried due to an inconsistent view of memory, does that also count as an "interruptible" moment for the runtime to poll for an async exception?

Overall I agree there is not a very significant distinction here, but I am curious about the nitty-gritty timings :)

Thanks!

**Comment by simonmar** [comment]
> (with async exceptions masked due to catch), the STM action might not retry, and if not, any pending asynchronous exception would not be delivered until after the transaction commits?

That's true, but you never have any guarantees about when an asynchronous exception will be delivered anyway.

I mean, strictly speaking you're probably right. I'll accept a pull request to fix it.

> A related question - if the transaction gets rolled back and retried due to an inconsistent view of memory, does that also count as an "interruptible" moment for the runtime to poll for an async exception?

I don't believe so.
