### ISSUE TITLE
The new `Internal` module is marked as `Trustworthy`.

### ISSUE THREAD

**Issue by phadej** [simonmar/async#151]
Safe Haskell is meant (among other things) to help prevent module abstraction violations, in that light, `.Internal` module should be `Unsafe`.

**Comment by simonmar** [comment]
I'm not sure I agree. Simply renaming a module does not affect its safety - Safe Haskell is for a very narrow purpose, namely to ensure the user can trust the type system and abstraction facilities provided by the language, it doesn't encompass any broader notion of safety.

**Comment by simonmar** [comment]
@phadej I think you might have a different interpretation of "Module encapsulation" than the intended one. Safe Haskell only promises that the semantics of abstraction are respected, it doesn't promise that you can't see the representation of a datatype by importing it from some other module.

**Comment by phadej** [comment]
> @phadej I think you might have a different interpretation of "Module encapsulation" than the intended one. Safe Haskell only promises that the semantics of abstraction are respected, it doesn't promise that you can't see the representation of a datatype by importing it from some other module.

Fair.

It seems that this is not 100% clear. `Data.Text.Internal` is unsafe (or rather not explicitly marked to be anything), but `Data.Set.Internal` are Trustworthy.

It seems we shouldn't assumedthat Safe Haskell code (i.e. importing only safe or trustworthy) modules cannot violate any internal invariants of data types, because there can be *trustworthy* way to break them.
