### ISSUE TITLE
`withAsync` should guarantee that the async will be canceled

### ISSUE THREAD

**Issue by Yuras** [simonmar/async#24]
Right now `cancel` can be interrupted by async exception. The example at the end demonstrates the issue. Either uninterruptibleMask should be used, or helper thread should be spawned to ensure eventual cancellation.

I prefer eventual guarantees to be provided by `cancel` itself.

I can prepare pull request if you agree with one of proposed solutions.

Current behavior is documented, so this issue is not a bug, but a feature request.

Note also, that `cancel` may throw even under `uninterruptibleMask` when canceling itself. So functions like `waitEitherCancel` leak orphan threads.

```haskell
-- uninterruptibleMask_ is used only to make the issue reproducible
main = do

  -- not killable for 5 sec
  let worker1 = do
        uninterruptibleMask_ $ threadDelay (5 * 1000 * 1000)
        forever $ do
          putStrLn "alive"
          threadDelay (1 * 1000 * 1000)

      worker2 =
        withAsync worker1 $ const $
          threadDelay (1 * 1000 * 1000)

  withAsync worker2 $ const $
    threadDelay (2 * 1000 * 1000)
  void getLine
```

In 1 sec after start `worker2` blocks trying to cancel `worker1`, but in 2 secs itself is interrupted by cancellation. In 5 secs `worker1` starts printing message indicating it is alive still.

**Comment by simonmar** [comment]
You're right, it should use `uninterruptibleMask`.  Want to make a pull request?  (sorry for the delay in looking at this, for some reason it got lost in my inbox)
