### ISSUE TITLE
Provide MonadIO instance for Concurrently

### ISSUE THREAD

**Issue by merijn** [simonmar/async#28]
I don't know if the dependency footprint of async is limited to base and stm on purpose, but it would be great if it was possible to add a dependency on transformers and implement a MonadIO instance for Concurrently, this would let Concurrently be used more easily in combination with other transformers.

For example, I just implemented a quick scraper for my own use where I used `ReaderT QSem Concurrently a` as my monad stack (the QSem to limit the amount of concurrent requests). This way I could simply use `traverse` instead of `mapConcurrently` to get the desired behaviour in an easy way. However, the lack of liftIO instances means that for more complicated monad stacks it becomes a hassle where one has to explicitly lift all the layers when using Concurrently at the bottom. This is easily avoided by a MonadIO instance so we can simply lift IO values through Concurrently into our stack.

```
instance MonadIO Concurrently where
    liftIO = Concurrently
```

**Comment by cohei** [comment]
`Concurrently` in master branch no longer has the `Monad` instance due to its invalid behavior. The details are here: #26. So `Concurrently` won't be a `MonadIO` either.
