### ISSUE TITLE
Support for base-4.9.0.0?

### ISSUE THREAD

**Issue by peti** [simonmar/async#36]
I tried compiling this library with GHC 8.0.1-rc1, but got a configure-time warning saying:

~~~
Setup: At least the following dependencies are missing:
base >=4.3 && <4.9
~~~~

It would be great to get a new `async` release that remedies this issue.

**Comment by simonmar** [comment]
There's already a new release that supports GHC 8.0: http://hackage.haskell.org/package/async

**Comment by peti** [comment]
Ah, I had not noticed the new release because I was following Stackage and they haven't picked up the new version yet because it's a major version bump. Sorry about that.
