### ISSUE TITLE
`uninterruptibleCancel` should be the default

### ISSUE THREAD

**Issue by bitonic** [simonmar/async#43]
Reasoning: we want to make the common case uninterruptible, since it will often be part of a cleanup operation, after which there is an expectation for the thread to be dead.

Basically, we're arguing that the issues that affected `withAsync` in #24 will affect most code using `cancel`.

**Comment by simonmar** [comment]
If the argument is that cancel should be uninterruptible inside a cleanup action, then I think this falls under the broader issue of whether cleanup actions should be uninterruptible by default.  I suggest that instead we clarify the documentation to say that if you're using `cancel` in a cleanup action, then you probably want `uninterruptibleCancel` instead.

**Comment by bitonic** [comment]
Right, the argument is:

* `cancel` needs to be uninterruptible in cleanup actions
* `cancel` most common use case is in cleanup actions
* Uninterruptible `cancel` is a safer default even outside cleanup actions

These things considered I think uninterruptible should be default, to minimize the chance of errors by people who just are not aware of the issue.

**Comment by simonmar** [comment]
Outside of a cleanup handler I don't think cancel needs to be uninterruptible at all.  After all, you can't tell the difference between an async exception that occurs just before the cancel and one that occurs during it.  Furthermore making cancel uninterruptible risks introducing deadlocks and programs that refuse to respond to ^C.  This could lead to *worse* outcomes for people who aren't aware of the issue.

**Comment by bitonic** [comment]
I mostly see it this way: `uninterruptibleCancel` by default will never on its own lead to incorrect code, but it might lead to bad behavior (unkillable processes) in the face of incorrect code -- when waiting on a deadlocked thread.

On the other hand interruptible `cancel` by default _will_ lead to incorrect code when using it in cleanup handlers. Since this incorrect code is very tricky to detect and debug (while a deadlock is at least evident), I'd much rather prefer to shield people from this even if they're not aware of it.

**Comment by Yuras** [comment]
I'm the original author of `uninterruptibleCancel`. I considered changing the default, but decided not to do that.

I agree that most uses of `cancel` are uninterruptible. But most of them live in the `async` package, because all other users use `withAsync`, `race`, `concurrently` etc (or *should* use them instead of hand-written variants). So I think most direct uses of `cancel` outside the package are probably outside of cleanups actions, where it'd be wrong to use `uninterruptibleCancel`. Anyway, that was my reasoning, I don't have very strong opinion.

**Comment by simonmar** [comment]
Ok, this is a debate that has reasonable arguments on both sides, and changing the default is not universally better.  So I'm going to leave the default as it is.  I'll accept a pull request to improve the docs if anyone wants to do that.
