### ISSUE TITLE
Expose Async constructor

### ISSUE THREAD

**Issue by mitchellwrosen** [simonmar/async#46]
Consider some code that races two IO actions that themselves have a cleanup action to perform:

```haskell
foo = bracket acquire1 release1 inner1
bar = bracket acquire1 release2 inner2

main = race_ foo bar
```

This will not necessarily leave time for `foo` and `bar` to complete `release1` and `release2` respectively.

I modified my code to essentially be:

```haskell
main = 
  bracket (async foo) cleanup
    (\a1 -> bracket (async bar) cleanup
      (\a2 -> waitEither_ a1 a2))

cleanup a = cancel a >> waitCatch a
```

Which is fine, but as a comment in the code mentions, this is slower than just combining the `async` and `bracket` manually, as `withAsync` does.

So, it would be nice to have access to the `Async` constructor so that `withAsync` can be written in user code!

**Comment by simonmar** [comment]
`withAsync` does what you want, I believe, after cb4bedca89c19a5a427e67c4aa1415337c839797

**Comment by mitchellwrosen** [comment]
It does! I didn't notice.
