### ISSUE TITLE
Add Monad instance for Concurrently

### ISSUE THREAD

**Issue by TravisWhitaker** [simonmar/async#48]
In light of the `ApplicativeDo` extension made available in GHC 8.0.1, I'd like to propose the following `Monad` instance for `Concurrently`.

```Haskell
instance Monad Concurrently where
    return = pure
    x >>= f = Concurrently $ runConcurrently x >>= (runConcurrently . f)
```

Where bind simply runs two `Concurrently` actions sequentially. This should allow one to write things of the form:

```Haskell
do x <- a
   y <- b
   f x y
```

The desugared expression will require `join`, and should allow `f` to wait on `a` and `b`, which may run concurrently.

**Comment by simonmar** [comment]
Isn't this the same as the Monad instance that was removed in bb1d405b6afc8a1cc73fa7cc8baeae28468dbed6?  It didn't satisfy the Monad laws so it was removed.

**Comment by TravisWhitaker** [comment]
Hmm, that's tricky indeed; I definitely would've been tripped up by that at some point.

For anyone else who wonders why this isn't possible #26 discusses the implications of `(<*>) /= ap` and [#38 from `either`](https://github.com/ekmett/either/pull/38) includes discussion of how Haxl deals with this issue.
