### ISSUE TITLE
Bounded Parallelism Feature

### ISSUE THREAD

**Issue by trbauer** [simonmar/async#49]
I'd love to have an async combinator that processes a list in chunks. The purpose is to allow the user to constrain the parallelism. E.g. if a task spawned has heavy requirements (e.g. calls readProcess or chews up an inordinate amount of memory or something), I want to limit the concurrent number to something lest I accidentally create a "fork bomb" or blow out the caches.

I've wired this up with async combinators a couple times and it's always a bit tricky (for me). An optimal implementation might do something with work stealing dynamically sliding the window of concurrent tasks as they finish out of order, but I am always happy enough just to synchronizing at each K (makes exception propagation and what not a little easier and also admits a bit more deterministic behavior).

**Comment by simonmar** [comment]
A better way to do what you want might be to use the `ParIO` monad: http://hackage.haskell.org/package/monad-par-0.3.4.8/docs/Control-Monad-Par-IO.html

**Comment by trbauer** [comment]
Thanks Simon, monad-par looks pretty cool. I have a similar monad concept
that I've written a couple times supporting both parallelism and
deferred/replayable IO. But I always implement it with a hand-rolled
function that uses async to limit the window of the parallelism.

In general how do you consider async to be different than monad-par (I.e
when does one choose one or the other)? Is it the determinism in monad-par?
- Tim

**Comment by simonmar** [comment]
Typically you would use `ParIO` when you want to limit the parallelism, because it has its own scheduler that uses at most N threads once (where N is set by `+RTS -N`).  There's also the `IVar` API for passing data between fragments of computation, which is useful when your problem has a non-trivial dataflow structure.
