### ISSUE TITLE
Is withAsync supposed to have spawn a masked thread / does async inherit masking state

### ISSUE THREAD

**Issue by ezyang** [simonmar/async#52]
bracket calls the resource initializer masked, and the documentation for withAsync suggests that if async inherits masking state (which it seems like it does, otherwise asyncWithUnmask would be pretty pointless), then the asynchronous thread runs with exceptions masked. This... doesn't seem intentional? Clarification would be nice.

**Comment by simonmar** [comment]
Good point.  The specification is wrong, but the implementation is correct: the masking state in the new thread is the same as it is at the call to `withAsync`.

We need to fix the spec and add a test to ensure it doesn't get broken in the future.

**Comment by ezyang** [comment]
Is a more correct spec?

```
withAsync action inner = mask $ \restore -> do
  a <- async (restore action)
  r <- restore inner `onException` cancel a
  cancel a
  return r
```

**Comment by simonmar** [comment]
As a spec, I think we can be simpler:

```
withAsync action inner = mask $ \restore -> do
  a <- async (restore action)
  restore inner `finally` cancel a
```

Even though this actually includes three `mask` calls.
