### ISSUE TITLE
Inconsistent behavior between cancel and cancelWith

### ISSUE THREAD

**Issue by glguy** [simonmar/async#53]
New in async-2.1.1 is that `cancel` will block until the thread finishes. This is probably a dangerous behavior change to slip in on a minor version bump, but that's a separate discussion. Now the behavior of `cancel` is inconsistent compared to `cancelWith`. Shouldn't these two agree with cancelWith merely being a generalization of cancel?

**Comment by simonmar** [comment]
You're right, I haven't been giving these changes careful enough scrutiny.  I'm snowed under with other things this week but I'll try to get to it soon.  CC @snoyberg

**Comment by bitonic** [comment]
@glguy you're right, I'll fix it.

**Comment by bitonic** [comment]
This is now fixed.
