### ISSUE TITLE
New cancel behavior hurts multiple tear downs

### ISSUE THREAD

**Issue by glguy** [simonmar/async#54]
The new cancel behavior in 2.1.1 has implications for operations like `waitAnyCancel`. These operations will no longer allow threads to teardown concurrently as they wait to cancel the next thread until the previous thread is completely finished. These operations should probably not be written in terms of `cancel` if its going to have this new behavior.

**Comment by simonmar** [comment]
I agree.  CC @snoyberg

**Comment by bitonic** [comment]
@glguy , what's the behavior that worries you? Is it a matter of performance -- e.g. you want the threads to terminate as quickly as possible -- or something else?

If the worry is performance we can write a combinator that cancels and waits for many `Async`s at once, although I'd argue it's an uncommon thing to trip on.

**Comment by simonmar** [comment]
I suggest we have a `cancelMany` that cancels multiple asyncs concurrently, and then use it everywhere we do multiple cancels, like `waitAnyCancel`.

**Comment by bitonic** [comment]
I'm not really sold on the usefulness of such a construct, it seems very unlikely to incur in problems because of the current behavior.

I'll implement it if I find the time, but I don't think it's high priority.

**Comment by treeowl** [comment]
There seem to be two possible approaches to `cancelMany`, with different tradeoffs. This lightweight version seems likely to be better than repeated `cancel` calls in cases where threads have non-trivial tear-down, without introducing much complexity or risking making matters significantly worse:

```haskell
cancelMany :: [Async a]
cancelMany asyncs = do
  mapM_ (\(Async t _) -> throwTo t AsyncCancelled) asyncs
  mapM_ waitCatch asyncs
```

This will deliver exceptions to the threads sequentially, and then wait for them sequentially. That means a thread stuck in an uninterruptible primop, `unsafe` FFI call, or `uninterruptibleMask` block could hold up the works, but (as I understand it) thread cleanup shouldn't do so. The heavy option
