### ISSUE TITLE
`withAsync` leaks space.

### ISSUE THREAD

**Issue by effectfully** [simonmar/async#58]
`withAsync action inner` keeps a reference for `action` until `inner` finishes.

```haskell
withAsyncUsing :: (IO () -> IO ThreadId)
               -> IO a -> (Async a -> IO b) -> IO b
withAsyncUsing doFork = \action inner -> do
  var <- newEmptyTMVarIO
  mask $ \restore -> do
    t <- doFork $ try (restore action) >>= atomically . putTMVar var
    let a = Async t (readTMVar var)
    r <- restore (inner a) `catchAll` \e -> do
      uninterruptibleCancel a -- here
      throwIO e
    uninterruptibleCancel a   -- and here
    return r
```

Here is a test case:

```
import Control.Concurrent
import Control.Concurrent.Async

testAsync :: IO ()
testAsync = do
  total <- newMVar 0
  let go 0 = takeMVar total
      go i = do
        t <- takeMVar total
        async . putMVar total $! t + i
        go (i - 1)
  go (100000 :: Int) >>= print

testWithAsync :: IO ()
testWithAsync = do
  total <- newMVar 0
  let go 0 = takeMVar total
      go i = do
        t <- takeMVar total
        withAsync (putMVar total $! t + i) $ \_ ->
          go (i - 1)
  go (100000 :: Int) >>= print
```

Running with `-O2 -threaded -rtsopts -with-rtsopts=-sstderr` gives for `testAsync` the following stats:

```
5000050000
     129,818,832 bytes allocated in the heap
         476,344 bytes copied during GC
          56,832 bytes maximum residency (2 sample(s))
          25,088 bytes maximum slop
               1 MB total memory in use (0 MB lost due to fragmentation)

                                     Tot time (elapsed)  Avg pause  Max pause
  Gen  0       249 colls,     0 par    0.008s   0.003s     0.0000s    0.0000s
  Gen  1         2 colls,     0 par    0.000s   0.000s     0.0001s    0.0001s

  TASKS: 4 (1 bound, 3 peak workers (3 total), using -N1)

  SPARKS: 0 (0 converted, 0 overflowed, 0 dud, 0 GC'd, 0 fizzled)

  INIT    time    0.000s  (  0.001s elapsed)
  MUT     time    0.384s  (  0.540s elapsed)
  GC      time    0.008s  (  0.003s elapsed)
  EXIT    time    0.000s  (  0.000s elapsed)
  Total   time    0.416s  (  0.543s elapsed)
```

and the following for `testWithAsync`:

```
5000050000
     173,941,664 bytes allocated in the heap
     434,310,464 bytes copied during GC
     104,267,376 bytes maximum residency (9 sample(s))
      10,062,504 bytes maximum slop
             216 MB total memory in use (0 MB lost due to fragmentation)

                                     Tot time (elapsed)  Avg pause  Max pause
  Gen  0       319 colls,     0 par    0.028s   0.046s     0.0001s    0.0003s
  Gen  1         9 colls,     0 par    0.084s   0.144s     0.0160s    0.0587s

  TASKS: 4 (1 bound, 3 peak workers (3 total), using -N1)

  SPARKS: 0 (0 converted, 0 overflowed, 0 dud, 0 GC'd, 0 fizzled)

  INIT    time    0.000s  (  0.001s elapsed)
  MUT     time    0.816s  (  0.889s elapsed)
  GC      time    0.112s  (  0.190s elapsed)
  EXIT    time    0.008s  (  0.018s elapsed)
  Total   time    0.960s  (  1.099s elapsed)
```

In order to circumvent this situation I'm using [an ugly (and largely untested) hack](http://lpaste.net/353087). The idea is that we have a mother thread that spawns child threads which register themselves in a shared `MVar`, run and then delete themselves as well. And if the mother thread finishes or dies, then all remaining child threads get cancelled. However, I couldn't implement this in a natural way, because the `Async` constructor is not exposed, hence the use of `mdo`. It also took me a while to figure out where and how my program leaks, so here are the requests:

1) Document this behaviour of `withAsync`. Or better improve it, if you know how.
2) Expose the `Async` constructor (via the `Control.Concurrent.Async.Internal` module for example), so people can easily extend the library without being forced to make a local clone.
3) If `withAsync` cannot be improved in this regard, could you suggest an idiomatic way to define an alternative to `withAsync` that doesn't leak? Some monad on top of `IO` (like in the lpaste above) would be fine.

**Comment by simonmar** [comment]
We could perhaps use a `Weak ThreadId`, although that would add overhead to `withAsync` in all cases, which is a shame.  It would be good to measure it though.

**Comment by nshimaza** [comment]
`withAsync` is essentially a sugar on `bracket` pattern.  `inner` block of `bracket` is surrounded by some `catch` family function so creating recursive call from inside of `inner` block results non-tail-recursive call.  I think that is the reason why your space leaks.
If my understanding is correct, `withAsync` is designed for different use cases than yours.  It seems the use case my package [thread-hierarchy](https://github.com/nshimaza/thread-hierarchy) addresses (in pretty straightforward but not elegant way) is similar to your case.
I'm quite new in Haskell so I can be wrong but hope this gives some clue.

**Comment by simonmar** [comment]
The original report isn't strictly correct - we're not retaining the whole `action`, only the `Async`, which points to the `ThreadId` of the (possibly dead) thread, and the STM action to wait for completion. The best we could do is use `Weak ThreadId`, but that would only save a little memory at the expense of lots of extra work to maintain the `Weak` pointers.  Also it would entail some API changes.

So overall I don't think we should do anything here. Feel free to re-open if you disagree.

**Comment by effectfully** [comment]
I should have said that the reference to the thread in which `action` runs is kept. Which prevents the thread's stack from being garbage collected. That's not a little memory, especially for a case where you nest `withAsync`s a lot like in my tests above.

At the very least the documentation should state clearly that `withAsync` is not for deep nesting.
How about adding another version (say, `withAsyncFinal`) that does free a finished thread in which `action` has run?

**Comment by simonmar** [comment]
I think `action` here is a red herring. There's a reference to the thread, but the thread doesn't necessarily keep `action` alive. (if you have evidence to the contrary, I'd be interested to investigate it).

I can add something to the docs though.

**Comment by effectfully** [comment]
No, I agree with you: once `action` is finished it should be GC'ed (unlike the thread (along with its stack) it was running in). It's just me being unable to express myself clearly.

**Comment by effectfully** [comment]
How about this version:

```haskell
withAsyncFineUsing :: (IO () -> IO ThreadId)
                   -> IO a -> (Async a -> IO b) -> IO b
withAsyncFineUsing doFork = \action inner -> do
  var <- newEmptyTMVarIO
  killVar <- newTVarIO (return ())
  mask $ \restore -> do
    t <- doFork $ try (restore action) >>= \e -> atomically $ do
      putTMVar var e
      writeTVar killVar (return ())
    let a = Async t (readTMVar var)
    atomically $ writeTVar killVar (uninterruptibleCancel a)
    let kill = join $ readTVarIO killVar
    r <- restore (inner a) `catchAll` \e -> do
      kill
      throwIO e
    kill
    return r
```

? Here we store a finalizer in the `killVar` variable. Once the child thread is finished, it puts `return ()` in the finalizer and thus the thread along with its stack can be garbage collected. Memory consumption is much better:

```
     176,811,208 bytes allocated in the heap
      26,177,944 bytes copied during GC
       7,987,288 bytes maximum residency (6 sample(s))
         480,152 bytes maximum slop
              14 MB total memory in use (0 MB lost due to fragmentation)

                                     Tot time (elapsed)  Avg pause  Max pause
  Gen  0       325 colls,     0 par    0.020s   0.036s     0.0001s    0.0008s
  Gen  1         6 colls,     0 par    0.020s   0.028s     0.0047s    0.0131s

  TASKS: 4 (1 bound, 3 peak workers (3 total), using -N1)

  SPARKS: 0 (0 converted, 0 overflowed, 0 dud, 0 GC'd, 0 fizzled)

  INIT    time    0.000s  (  0.001s elapsed)
  MUT     time    1.432s  (  2.094s elapsed)
  GC      time    0.040s  (  0.064s elapsed)
  EXIT    time    0.004s  (  0.002s elapsed)
  Total   time    1.568s  (  2.161s elapsed)

  Alloc rate    123,471,513 bytes per MUT second

  Productivity  97.4% of total user, 70.7% of total elapsed

gc_alloc_block_sync: 0
whitehole_spin: 0
gen[0].sync: 0
gen[1].sync: 0
```

14 MB against 216 MB at the cost of adding an additional `TVar` .

What do you think?
