### ISSUE TITLE
STM exceptions are not written to result MVar

### ISSUE THREAD

**Issue by nmattia** [simonmar/async#62]
it looks like `concurrently` (the `MVar` version) has some issues rethrowing STM exceptions. Take the following program:

```
import Control.Concurrent.STM
import Control.Concurrent.Async
import Control.Monad

main :: IO ()
main = do
  tvar <- newTVarIO False :: IO (TVar Bool)
  void $ join (concurrently) (atomically $ readTVar tvar >>= check)
```
when run (with full RTS, i.e. not in ghci):

```
$ stack runghc async.hs
[1 of 1] Compiling Main             ( async.hs, async.o )
Linking async ...
$./async 
async: thread blocked indefinitely in an MVar operation
```
however it's not about the exception itself:
```
λ: join (concurrently) (throwIO BlockedIndefinitelyOnSTM)
*** Exception: thread blocked indefinitely in an STM transaction
```
inspecting (and adding logging to) the `async` code, it looks like the exception is never written to the `MVar` that's supposed to communicate it back to the main thread. The exception is thrown here: https://github.com/simonmar/async/blob/d7ea6dd509d6958e9ab7c40bf79a139b137f205f/Control/Concurrent/Async.hs#L608

I have no idea why this would be the case. Pinging @qnikst who helped during debugging.

**Comment by qnikst** [comment]
From debug log I see, that all 3 threads receives an exception about being blocked, it seems that
RTS thinks that there are no threads that can write to the `MVar`, despite the `catch`
```
cap 0: thread 1 stopped (blocked on an MVar)
        thread    1 @ 0x200005388 ["main"] is blocked on an MVar @ 0x2000041d0 (TSO_DIRTY)
cap 0: running thread 2 (ThreadRunGHC)
cap 0: thread 2 has label left
cap 0: thread 2 stopped (blocked on an MVar)
        thread    2 @ 0x2000059d0 ["left"] is blocked on an MVar @ 0x2000041a0 (TSO_DIRTY)
cap 0: running thread 3 (ThreadRunGHC)
cap 0: thread 3 stopped (yielding)
cap 0: running thread 3 (ThreadRunGHC)
cap 0: thread 3 has label right
cap 0: thread 3 stopped (blocked on an MVar)
        thread    3 @ 0x200005dd0 ["right"] is blocked on an MVar @ 0x2000041a0 (TSO_DIRTY)
...
cap 0: GC done
resurrecting thread 1
cap 0: raising exception in thread 1.
resurrecting thread 2
cap 0: raising exception in thread 2.
resurrecting thread 3
cap 0: raising exception in thread 3.
cap 0: all caps stopped for GC
cap 0: finished GC

```

**Comment by nmattia** [comment]
Actually it's not only STM, same behavior with `MVar`s:

```
import Control.Concurrent.STM
import Control.Concurrent.MVar
import Control.Concurrent.Async
import Control.Monad
import Control.Exception

main :: IO ()
main = do
  tvar <- newTVarIO False :: IO (TVar Bool)
  mvar <- newEmptyMVar:: IO (MVar ())
  putStrLn "foo"
  void $ join (concurrently) (handle handleSTM $ throwIO BlockedIndefinitelyOnSTM)
  putStrLn "bar"
  void $ join (concurrently) (handle handleMVar $ readMVar mvar)
  putStrLn "baz"
  void $ join (concurrently) (handle handleSTM $ atomically $ readTVar tvar >>= check)
  where
    handleSTM :: BlockedIndefinitelyOnSTM -> IO ()
    handleSTM _ = return ()
    handleMVar :: BlockedIndefinitelyOnMVar -> IO ()
    handleMVar _ = return ()
```
Outputs the following:
```
foo
bar
async.hs: thread blocked indefinitely in an MVar operation
```
It also appears that I can't catch the exceptions myself either.
(same if the `mvar` line is removed)

**Comment by qnikst** [comment]
Stupid (and incorrect change) by using ``takeMVar done `catch` (\BlockedIndefinitelyOnMVar -> takeMVar done)`` leads to expected behavior.

**Comment by Yuras** [comment]
@qnikst Why the change is incorrect? It should probably be more careful to handle `BlockedIndefinitelyOnMVar` is the second `takeMVar`, like [here](https://github.com/simonmar/async/blob/d7ea6dd509d6958e9ab7c40bf79a139b137f205f/Control/Concurrent/Async.hs#L283), but otherwise it seems to be valid solution.

The behavior of `BlockedIndefinitelyOnMVar` and `BlockedIndefinitelyOnSTM` is correct, though not intuitive, see [here](https://ghc.haskell.org/trac/ghc/ticket/5055).

**Comment by qnikst** [comment]
@Yuras I found that fix not complete, with current throw to all blocked threads semantics. say if we have double layer of deadlock, something along 

```haskell
  let block = atomically $ readTVar tvar >>= check
  in void $ join (concurrently) (block `finally` block)
```

in this case we will still see same behavior. I think I'll send that fix anyway now, because it's still an improvement for the common case.

**Comment by qnikst** [comment]
@Yuras  @simonmar https://github.com/simonmar/async/issues/14#issuecomment-51029321 there is seems a better solution, that will make caller thread immutable to BlockedIndefinitely exception, and it seems it will cover all possible cases in calls that are using `concurrently'` are there any downsides in going that way by default?

**Comment by simonmar** [comment]
I haven't investigated this thoroughly, but is the conclusion that `concurrently` doesn't respect its specification in terms of `withAsync`, because it needs an equivalent to the special handling that we added to `waitCatch` to handle deadlock exceptions?  That would make sense to me.

**Comment by simonmar** [comment]
cc @snoyberg

**Comment by Yuras** [comment]
@simonmar Yes, I believe it doesn't respect the spec. Right now it fails with:

> thread blocked indefinitely in an MVar operation

If I enable `USE_ASYNC_VERSIONS` (and fix trivial build error), then it fails with:

> thread blocked indefinitely in an STM transaction

Though I don't think it is directly related to the fix in `waitCatch` because `concurrently` uses `waitBoth` instead.
