### ISSUE TITLE
link memory leak

### ISSUE THREAD

**Issue by eminglorion** [simonmar/async#7]
Usage of <code>link</code> may lead to a memory leak. Here is a test case:

``` haskell
module Main where

import Control.Concurrent
import Control.Concurrent.Async
import Control.Monad

main = do
  to <- async $ forever $ threadDelay 50000000
  forever $ do
    async $ link to >> return ()
```

I believe the problem is <code>link</code> waits only for an async and doesn't check a thread it should kill. Then <code>link</code> thread still lives even if it's not needed anymore.

**Comment by mgsloan** [comment]
I also needed something like this `dependsOn`.  Thankfully, it's possible to write one externally to the async lib.  Here's what I ended up with by copy / modifying code from async:

```haskell
-- | Like 'link2', but exceptions are thrown from the left thread to
-- the right, but not the other way around.
link1 :: Async a -> Async b -> IO ()
link1 left right =
    void $ forkRepeat $ do
        r <- waitEitherCatch left right
        case r of
            Right (Left e) -> cancelWith right e
            _ -> return ()
  where
    -- Copied from Control.Concurrent.Async
    forkRepeat :: IO a -> IO ThreadId
    forkRepeat action =
      mask $ \restore ->
        let go = do r <- tryAll (restore action)
                    case r of
                      Left _ -> go
                      _      -> return ()
        in forkIO go
    tryAll :: IO a -> IO (Either SomeException a)
    tryAll = try
```

Not sure about the name, but `linkTo` was rather phonetically ambiguous with `link2`.  If consistency with the other `link` functions is disregarded, then I'd call it `rethrowTo`, or something along those lines.

**Comment by simonmar** [comment]
I don't think we should do anything here. The original test case repeatedly links the current thread to a thread that will never return, building up an unbounded number of linkages, which will clearly use up all the memory.
