### ISSUE TITLE
Idea: Give Async a Monad and MonadPlus instance

### ISSUE THREAD

**Issue by ChristopherKing42** [simonmar/async#70]
We would need to add a `Pure :: a -> Async a` data constructor to `Async`, but other than that, the current `Async` type supports the `Monad` and `MonadPlus` typeclasses. This is because `STM` is a `Monad` and `MonadPlus`.

`return` would equal `Pure`, obviously. `Pure a >>= f = f a`. For `x >>= f` where `x` isn't `Pure`, we give the resulting async `x`'s `asyncThreadId`, and use the `STM` monad to generate the resulting `_asyncWait`.

The `MonadPlus` instance would be similar, with `mzero` corresponding to `STM`'s `mzero` (and some junk `ThreadId`) and `mplus` corresponding to `STM`'s `mplus` (and choosing the left `ThreadId` (or `mzero`'s `ThreadId`).

If you don't want to add a new data constructor to `Async`, you can also define an `Applicative` and Alternative instance without changing the type at all. `pure a` would have a junk `asyncThreadId` and would use `STM`'s pure for `asyncThreadId`. `<*>` would use `STM`'s `<*>` for `_asyncWait`, and would choose the left-most non-junk-`asyncThreadId` for the resulting `asyncThreadId`. `Alternative` would work similarly. (If you do not like using an invalid `ThreadId` for `asyncThreadId`, you could slightly change `asyncThreadId`'s type and use `Nothing` instead. Or you could make it a `[ThreadId]` of all the threads involved.)

**Comment by simonmar** [comment]
See discussion in #71
