### ISSUE TITLE
Build error of async 2.1.1.1 on GHC 8.4.1-alpha1

### ISSUE THREAD

**Issue by asr** [simonmar/async#77]
GHC 8.4.1-alpha1 was [announced](https://mail.haskell.org/pipermail/ghc-devs/2017-December/015235.html). While testing [Agda](https://github.com/agda/agda) with this version of GHC, I got the following error:

```
$ cabal install
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: async-2.1.1.1 (user goal)
next goal: base (dependency of async-2.1.1.1)
rejecting: base-4.11.0.0/installed-4.1... (conflict: async => base>=4.3 &&
<4.11)
...
```

The current version on the master branch (commit  08d2f33) compiles with GHC 8.4.1-alpha1, so could you make a release, please?

Blocking https://github.com/agda/agda/issues/2878.

**Comment by simonmar** [comment]
Just released 2.2.1 which should fix this.
