### ISSUE TITLE
cocurrently cause memory leak

### ISSUE THREAD

**Issue by highfly22** [simonmar/async#80]
I use Control.Concurrent.Async.concurrently_ to combine two service IO monad. A memory leak occurs.

My code looks like the following:

`concurrently_ (server (show port))  $  loop metric`

Using forkIO instead, there is no memory leak.

```
do
   forkIO $ server (show port)
   loop metric
```

I don't think this is a bug of async. Just record this issue in here.

![_20180301160935](https://user-images.githubusercontent.com/1296264/36833618-056477d4-1d6b-11e8-977f-c41a66b0630d.png)

**Comment by simonmar** [comment]
Thanks for reporting this. Is it possible to provide us with a standalone test case to demonstrate the issue?

> I don't think this is a bug of async. Just record this issue in here.

Interesting - why don't you think it's a bug?

**Comment by highfly22** [comment]
I found this [question](https://stackoverflow.com/questions/41306593/memory-leak-in-recursive-io-function-pap) in the stackoverflow. I used the simlar IO loop, then a memory leak is expected. But using function concurrently_ makes thing worse.

Here is simplified code.

```
import           Network.Simple.TCP
import           Control.Concurrent.Async (concurrently_)

server :: String -> IO ()
server port = do
  serve (Host "127.0.0.1") port $ \(conn, _) -> do
     ...

data Metric = Metric !Int !Int

loop :: Metric -> IO ()
loop metric = do
   newmetric <- getMetric
   print $ diffMetric newmetric metric
   loop newmetric

main = do
   metric <- getMetric
   concurrently_   (server "123") $ loop metric
```
