### ISSUE TITLE
`race` behaves differently from its simple implementation

### ISSUE THREAD

**Issue by gromakovsky** [simonmar/async#81]
Consider the following code: https://gist.github.com/gromakovsky/018b4169ae2ab2adffd744ce6d510f3a
There I defined `race0` using the same code as in [the documentation](https://hackage.haskell.org/package/async-2.2.1/docs/Control-Concurrent-Async.html#v:race).
When I launch it (using `stack async-strange-race.hs`) and press `Ctrl-C`, `release B` is printed and `release main` is printed in a second. That's exactly what I expect.
However, if I change `race0` to actual `race`, the behavior is different. `release B` and `release main` are printed concurrently, there is no delay (should be 1 second) and the output is sometimes messy (something like `relreealseea sBe`).
It looks like a significant inconsistency to me. Is it a bug?

**Comment by Yuras** [comment]
`lts-9.1` has `async-2.1.1.1` which is a bit old. Did you try the latest version from Hackage? The issue looks very similar to #59, which is fixed in `2.2.1`.

**Comment by gromakovsky** [comment]
Thanks, @Yuras! I tested with `2.2.1` and there is no such problem. Sorry for this noise.
