### ISSUE TITLE
Confusing error message

### ISSUE THREAD

**Issue by wyager** [simonmar/async#92]
I ran into some behavior that threw me off for a bit:

```haskell
import Control.Concurrent.MVar
import Control.Concurrent.Async

main :: IO ()
main = takeMVar =<< newEmptyMVar
```

As expected:

    dalloc-exe: thread blocked indefinitely in an MVar operation

```haskell
import Control.Concurrent.MVar
import Control.Concurrent.Async

main :: IO ()
main = wait =<< async (takeMVar =<< newEmptyMVar)
```

    dalloc-exe: thread blocked indefinitely in an STM transaction

I suppose this is *technically* true, but it seems a bit misleading to "transmute" the blocked-on-MVar exception into a blocked-on-STM exception. Would it make sense/is it straightforward to make this re-throw the original error instead?

**Comment by simonmar** [comment]
Hmm, it seems that we added a workaround for this to `waitCatch` but not to `wait`: https://github.com/simonmar/async/pull/15
