### ISSUE TITLE
compareAsyncs description not clear

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [simonmar/async#97]
The description "Compare two Asyncs that may have different types" for compareAsyncs does not seem to describe what is being compared.

I am not sure if this is correct but would it be more accurate to say "Compare two Asyncs that may have different types by their ThreadId."

**Comment by simonmar** [comment]
Sure, want to submit a PR?

**Comment by BebeSparkelSparkel** [comment]
pr #99
